const API='https://api.alquran.cloud/v1';
const $=s=>document.querySelector(s);
const surahNames=['الفاتحة','البقرة','آل عمران','النساء','المائدة','الأنعام','الأعراف','الأنفال','التوبة','يونس','هود','يوسف','الرعد','إبراهيم','الحجر','النحل','الإسراء','الكهف','مريم','طه','الأنبياء','الحج','المؤمنون','النور','الفرقان','الشعراء','النمل','القصص','العنكبوت','الروم','لقمان','السجدة','الأحزاب','سبأ','فاطر','يس','الصافات','ص','الزمر','غافر','فصلت','الشورى','الزخرف','الدخان','الجاثية','الأحقاف','محمد','الفتح','الحجرات','ق','الذاريات','الطور','النجم','القمر','الرحمن','الواقعة','الحديد','المجادلة','الحشر','الممتحنة','الصف','الجمعة','المنافقون','التغابن','الطلاق','التحريم','الملك','القلم','الحاقة','المعارج','نوح','الجن','المزمل','المدثر','القيامة','الإنسان','المرسلات','النبأ','النازعات','عبس','التكوير','الانفطار','المطففين','الانشقاق','البروج','الطارق','الأعلى','الغاشية','الفجر','البلد','الشمس','الليل','الضحى','الشرح','التين','العلق','القدر','البينة','الزلزلة','العاديات','القارعة','التكاثر','العصر','الهمزة','الفيل','قريش','الماعون','الكوثر','الكافرون','النصر','المسد','الإخلاص','الفلق','الناس'];
let allSurahs=[];
async function api(path){const r=await fetch(API+path);if(!r.ok)throw new Error('API');const j=await r.json();return j.data}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function setLoading(el,msg='جارٍ التحميل…'){el.innerHTML=`<div class="loading">${msg}</div>`}
async function loadSurahs(){try{allSurahs=await api('/surah');$('#surahGrid').innerHTML=allSurahs.map(s=>`<article class="surah" data-id="${s.number}"><span class="surah-num">${s.number}</span><div><strong>${escapeHtml(s.name)}</strong><small>${s.revelationType==='Meccan'?'مكية':'مدنية'} • ${s.numberOfAyahs} آية</small></div></article>`).join('');document.querySelectorAll('.surah').forEach(x=>x.onclick=()=>openSurah(+x.dataset.id))}catch(e){$('#surahGrid').innerHTML='<div class="results-empty">تعذر تحميل السور الآن. تحقق من اتصال الإنترنت.</div>'}}
async function openSurah(id){const modal=$('#readerModal');modal.classList.add('open');setLoading($('#readerBody'));try{const s=await api(`/surah/${id}/quran-uthmani-quran-academy`);$('#readerTitle').textContent=s.name;$('#readerMeta').textContent=`${s.revelationType==='Meccan'?'مكية':'مدنية'} • ${s.numberOfAyahs} آية`;$('#readerBody').innerHTML=s.ayahs.map(a=>`<article class="ayah" id="ayah-${a.numberInSurah}"><div class="ayah-tools"><span>${a.numberInSurah}</span><button data-copy="${encodeURIComponent(a.text)}">نسخ</button><button data-audio="${a.number}">▶ استماع</button></div><p>${escapeHtml(a.text)} <span class="ayah-end">۝${a.numberInSurah}</span></p></article>`).join('');document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>navigator.clipboard?.writeText(decodeURIComponent(b.dataset.copy)));document.querySelectorAll('[data-audio]').forEach(b=>b.onclick=()=>playAyah(+b.dataset.audio));window.scrollTo({top:0,behavior:'smooth'})}catch(e){setLoading($('#readerBody'),'تعذر تحميل السورة. حاول مرة أخرى.')}}
function closeReader(){$('#readerModal').classList.remove('open');$('#audioPlayer').pause()}
function playAyah(n){const p=$('#audioPlayer');p.src=`https://cdn.islamic.network/quran/audio/128/ar.alafasy/${n}.mp3`;p.play().catch(()=>{})}
async function searchQuran(term){term=term.trim();if(!term)return;location.hash='search';const box=$('#results');$('#resultTitle').textContent=`نتائج البحث عن «${term}»`;setLoading(box,'جاري البحث في القرآن الكريم…');try{const data=await api(`/search/${encodeURIComponent(term)}/all/ar`);const matches=(data.matches||[]).filter(x=>x.edition?.type==='quran');box.innerHTML=matches.length?matches.map(x=>`<article class="result"><span class="ref">سورة ${escapeHtml(x.surah.name)} — الآية ${x.numberInSurah}</span><p>${escapeHtml(x.text)}</p><button class="open-result" data-surah="${x.surah.number}">فتح السورة</button></article>`).join(''):'<div class="results-empty">لم نجد نتائج مطابقة. جرّب كلمة أخرى.</div>';document.querySelectorAll('.open-result').forEach(b=>b.onclick=()=>openSurah(+b.dataset.surah))}catch(e){box.innerHTML='<div class="results-empty">تعذر تنفيذ البحث حاليًا. تحقق من اتصال الإنترنت.</div>'}}
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();searchQuran($('#searchInput').value)});
$('#themeBtn').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('quran-theme',document.body.classList.contains('dark')?'dark':'light')});
if(localStorage.getItem('quran-theme')==='dark')document.body.classList.add('dark');
document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>searchQuran(b.dataset.topic));
$('#closeReader').onclick=closeReader;$('#readerModal').addEventListener('click',e=>{if(e.target.id==='readerModal')closeReader()});
$('#randomBtn')?.addEventListener('click',async()=>{try{const a=await api('/ayah/random/quran-uthmani-quran-academy');openSurah(a.surah.number)}catch(e){}});
loadSurahs();