const $=id=>document.getElementById(id);
function getFavs(){return JSON.parse(localStorage.getItem('egyptFavs')||'[]')}
function saveFavs(a){localStorage.setItem('egyptFavs',JSON.stringify(a));$('favCount').textContent=a.length}
function card(x){const fav=getFavs().includes(x.id);return `<article class="card" onclick="openArtifact(${x.id})"><div class="card-img" style="background-image:url('${x.image}')"><button class="card-fav" onclick="toggleFav(event,${x.id})">${fav?'♥':'♡'}</button></div><div class="card-body"><span class="tag">${x.era} • ${x.type}</span><h3>${x.name}</h3><div class="meta">📍 ${x.governorate} • ${x.date}</div><p>${x.text}</p><span class="read">عرض الملف الكامل ←</span></div></article>`}
function filtered(){const q=($('search').value||'').trim().toLowerCase(),era=$('era').value,type=$('type').value,g=($('governorate').value||'').trim().toLowerCase();return artifacts.filter(x=>(!q||(x.name+x.ancientName+x.text+x.location+x.governorate).toLowerCase().includes(q))&&(!era||x.era===era)&&(!type||x.type===type)&&(!g||x.governorate.toLowerCase().includes(g)))}
function render(){const a=filtered();$('cards').innerHTML=a.length?a.map(card).join(''):'<div class="empty">لا توجد نتائج مطابقة. جرّب كلمة بحث أو فلترًا آخر.</div>';saveFavs(getFavs());}
function liveSearch(){render()}
function searchArtifacts(){$('explore').scrollIntoView({behavior:'smooth'});render()}
function setFilter(era){$('era').value=era; $('search').value=''; $('explore').scrollIntoView({behavior:'smooth'});render()}
function toggleFav(e,id){e.stopPropagation();const f=getFavs(),i=f.indexOf(id);i>-1?f.splice(i,1):f.push(id);saveFavs(f);render()}
function showFavorites(){const f=getFavs();const a=artifacts.filter(x=>f.includes(x.id));$('cards').innerHTML=a.length?a.map(card).join(''):'<div class="empty">لم تحفظ أي أثر بعد. اضغط ♡ على أي بطاقة لحفظها.</div>';$('explore').scrollIntoView({behavior:'smooth'})}
function openArtifact(id){const x=artifacts.find(a=>a.id===id);if(!x)return;const f=getFavs().includes(id);$('modalContent').innerHTML=`<div class="detail-img" style="background-image:url('${x.image}')"></div><div class="detail"><span class="tag">${x.era} • ${x.type}</span><h2>${x.name}</h2><p>${x.text}</p><div class="detail-grid"><div><b>الاسم القديم</b><br>${x.ancientName}</div><div><b>الموقع</b><br>${x.location}</div><div><b>المحافظة</b><br>${x.governorate}</div><div><b>التاريخ</b><br>${x.date}</div><div><b>الغرض</b><br>${x.purpose}</div><div><b>العمارة</b><br>${x.architecture}</div></div><a class="source" target="_blank" href="${x.source}">المصدر / المرجع ↗</a><div class="detail-actions"><button onclick="toggleFav(event,${x.id});openArtifact(${x.id})">${f?'إزالة من المحفوظات':'♡ حفظ في المفضلة'}</button></div></div>`;$('modal').classList.add('show')}
function closeModal(e){if(!e||e.target===$('modal')||e.target.classList.contains('close'))$('modal').classList.remove('show')}
document.addEventListener('keydown',e=>{if(e.key==='Escape')$('modal').classList.remove('show')});
$('statSites').textContent=artifacts.length+'+';
saveFavs(getFavs());render();